---

- name: install OpenHPC repository
  yum:
    name: "{{ slurm_ohpc_version }}"
  tags: slurm

- name: increase resource limits
  pam_limits:
    domain: "{{ item.domain }}"
    limit_type: "{{ item.limit_type }}"
    limit_item: "{{ item.limit_item }}"
    value: "{{ item.value }}"
  loop: "{{ slurm_limits }}"
  tags: slurm

- name: copy sysctl configuration
  copy:
    src: slurmctld/sysctl.conf
    dest: /etc/sysctl.d/98-macc.conf
    mode: 0644
  register: result
  tags: slurm

- name: reload sysctl configuration
  command: /usr/sbin/sysctl -p
  when: result.changed
  tags: slurm

- name: install packages
  yum:
    name: "{{ packages }}"
  vars:
    packages:
      - slurm-slurmctld-ohpc
      - slurm-example-configs-ohpc
      - mailx
  tags: slurm

- name: create directories
  file:
    path: "{{ item }}"
    state: directory
    mode: 0755
    owner: "{{ slurm_user }}"
    group: "{{ slurm_group }}"
  loop:
    - "{{ slurm_logdir }}"
  tags: slurm

- name: copy Slurm configuration
  template:
    src: slurm.conf
    dest: /etc/slurm/slurm.conf
    owner: "{{ slurm_user }}"
    group: "{{ slurm_group }}"
    mode: 0644
  notify: restart slurmctld
  tags: slurm

- name: copy cgroup configuration
  template:
    src: cgroup.conf
    dest: /etc/slurm/cgroup.conf
    owner: "{{ slurm_user }}"
    group: "{{ slurm_group }}"
    mode: 0644
  notify: restart slurmctld
  tags: slurm

- name: start Slurm service
  service:
    name: slurmctld
    state: started
    enabled: yes
  tags: slurm
